dist: trusty
addons:
  apt:
    sources:
      - sourceline: "deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-8.0"
        key_url: https://raw.githubusercontent.com/travis-ci/apt-source-safelist/master/keys/mysql-5.7-trusty.asc
    packages:
      - mysql-community-client
      - mysql-community-server
      - mysql-community-client-core
      - mysql-community-server-core
      - mysql-client
      - mysql-server
      - mysql-common
      - libmysqlclient-dev
      - libmysqlclient21
      - libstdc++6
      - libssl1.0.0
      - libmecab2
      - init-system-helpers
services:
  - mysql
sudo: true
before_install:
  - mysql -e 'CREATE DATABASE auditoriums_test;'
  - mysql -u root -e "CREATE USER 'kernel'@'localhost' IDENTIFIED BY '${dbPass}';"
  - mysql -u root -e "GRANT ALL ON auditoriums_test.* TO 'kernel'@'localhost';"
language: java
jdk:
  - oraclejdk8
script:
  - cd backend
  - ./mvnw clean compile test
