dist: trusty
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE auditoriums_test;'
  - mysql -u root -e "CREATE USER 'kernel'@'localhost' IDENTIFIED BY '${dbPass}';"
  - mysql -u root -e "GRANT ALL ON auditoriums_test.* TO 'kernel'@'localhost';"
language: java
jdk:
  - oraclejdk8
sudo: false
script:
  - cd backend
  - ./mvnw clean compile test
