CREATE TABLE IF NOT EXISTS `lecturer` (
    `id` BIGINT NOT NULL,
    `position` VARCHAR(50) NOT NULL,
    FOREIGN KEY (`id`) REFERENCES `user`(id) ON DELETE CASCADE)
ENGINE=InnoDB DEFAULT CHARSET=utf8;